name: build

on: push

jobs:
  ubuntu_cuda10-1:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: |
        git submodule update --init --recursive
        conda config --add channels conda-forge
        conda install -y conda-build
        conda info
        URL=http://developer.download.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.243_418.87.00_linux.run
        wget -q --show-progress --progress=bar:force:noscroll $URL -O cuda.run
        sudo sh cuda.run --toolkit --silent
        ls /usr/local
    - name: conda-build
      run: |
        export CUDA_VERSION=10.1
        conda build conda-recipe
  
  # windows_cuda10-1:

  #   runs-on: windows-latest

  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: lists
  #     run: |
  #       $env:CUDA_VERSION = "10.1"
  #       cmd.exe /c 'C:\Miniconda\Scripts\activate.bat'
  #       C:\Miniconda\condabin\conda.bat config --set always_yes true
  #       C:\Miniconda\condabin\conda.bat config --add channels conda-forge
  #   - name: setup
  #     continue-on-error: true
  #     run: |
  #       C:\Miniconda\condabin\conda.bat install conda-build
  #       C:\Miniconda\condabin\conda.bat info --all
  #   # - name: install cudatoolkit
  #   #   shell: bash
  #   #   run: |
  #   #     URL=http://developer.download.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.243_426.00_win10.exe
  #   #     curl -o cuda.exe "$URL"
  #   #     ./cuda.exe -s
  #   - name: conda-build
  #     run: |
  #       $env:CUDA_VERSION = "10.1"
  #       C:\Miniconda\condabin\conda.bat build conda-recipe